### ISSUE TITLE
No IE 11 support

### ISSUE THREAD

**Issue by mastertinner** [fabulator/locales-detector#47]
The https://github.com/fabulator/locales-detector/blob/master/.browserslistrc file explicitly says not to support IE 11 and below. Unfortunately, IE 11 is still supported by Microsoft and used in many larger enterprises. Would it be possible / make sense to remove this line from the `.browserslistrc` file? The default file for the [Vue CLI](https://cli.vuejs.org/) for example looks as follows:

```txt
> 1%
last 2 versions
```

**Comment by fabulator** [comment]
That is reasonable. I published new minor version 2.1.0 on npm with removed lines and recompiled build. I don't want to use "last 2 versions" because it would also add support for IE 10.

**Comment by mastertinner** [comment]
Nice. Thanks for the quick fix!
